services:
  # A Docker web service
  - type: web
    name: alist
    env: docker
    repo: https://github.com/stevessrbackup/bli-render-render.git # optional
    region: singapore # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8088
      - key: DB_TYPE
        value: postgresql
      - key: DB_HOST
         value: db.bit.io
        sync: false
      - key: DB_PORT
         value: 5432
      - key: DB_USER
         value: stevessr
        sync: false
      - key: DB_PASS
         value: v2_44UCS_SDkqDbgH9Q6TnQRUKc8WkHr
        sync: false
      - key: DB_NAME
         value: stevessr/steve
        sync: false
      - key: DB_TABLE_PREFIX
        value: Bli_
      - key: CDN
        value: https://npm.elemecdn.com/alist-web@$version/dist
